<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="Hiwebinterface"
     targetNamespace="http://practicetest.com/FMW/HiSOA/Hiwebinterface"
     xmlns:tns="http://practicetest.com/FMW/HiSOA/Hiwebinterface"
     xmlns:inp1="http://practicetest.com/requestxsd"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://practicetest.com/requestxsd" schemaLocation="../Schemas/Request_Response.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="req" element="inp1:Request"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="Resp" element="inp1:Response"/>
    </wsdl:message>
    <wsdl:portType name="Hi_Interface">
        <wsdl:operation name="HiOSB">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
